version: '3.8'

services:
  frontend:
    build:
      context: ./diary
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./diary:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    command: gunicorn your backend.wsgi:application --bind 0.0.0.0:8000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: POSTGRESS_PASSWORD
      POSTGRES_DB: diary
    ports:
      - "5432:5432"